<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>body_message_terms</name>
   <tag></tag>
   <elementGuidId>b2b2dc5e-45a2-41be-9c59-ca0908ecb92c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>body</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*/text()[normalize-space(.)='This is the terms and conditions document. We are not yet ready with it. Stay tuned!']/parent::*</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>body</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>This is the terms and conditions document. We are not yet ready with it. Stay tuned!Capture object: Alt ` ● Load DOM Map: Ctrl Alt ` /html[1]/body[1]</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='This is the terms and conditions document. We are not yet ready with it. Stay tuned!']/parent::*</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//body</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//body[(text() = 'This is the terms and conditions document. We are not yet ready with it. Stay tuned!Capture object: Alt ` ● Load DOM Map: Ctrl Alt ` /html[1]/body[1]' or . = 'This is the terms and conditions document. We are not yet ready with it. Stay tuned!Capture object: Alt ` ● Load DOM Map: Ctrl Alt ` /html[1]/body[1]')]</value>
   </webElementXpaths>
</WebElementEntity>
